const SITE_CONFIG = {
  brand: {
    name: "Puntano Web",
    summary:
      "Diseñamos paginas web modernas y efectivas para ayudar a tu negocio a crecer.",
    copyright: "(c) 2026 Puntano Web. Todos los derechos reservados.",
  },
  contact: {
    whatsappNumber: "5491132595957",
    whatsappMessage:
      "Hola Puntano Web, quiero consultar por una pagina web para mi negocio.",
    email: "satiago@puntanoweb.com",
    phone: "+54 9 11 3259-5957",
    address: "San Luis, Argentina",
  },
  links: {
    home: "#inicio",
    portfolio: "#trabajos",
    instagram: "https://www.instagram.com/puntanoweb",
    facebook: "https://www.facebook.com/puntanoweb",
    linkedin: "https://www.linkedin.com/company/puntanoweb",
  },
  navigation: [
    { label: "Inicio", href: "#inicio" },
    { label: "Servicios", href: "#servicios" },
    { label: "Trabajos", href: "#trabajos" },
    { label: "Nosotros", href: "#nosotros" },
    { label: "Contacto", href: "#contacto" },
  ],
  footerServices: [
    "Sitios web",
    "SEO y posicionamiento",
    "Rediseño web",
    "Mantenimiento",
  ],
  services: [
    {
      title: "Diseño y desarrollo web",
      text: "Landing pages y sitios web profesionales, modernos y adaptados a todos los dispositivos.",
      icon: "monitor",
    },
    {
      title: "Posicionamiento en Google",
      text: "Optimizamos tu web para que te encuentren en buscadores y tengas más visitas.",
      icon: "magnifying-glass",
    },
    {
      title: "Publicidad en Google Ads",
      text: "Creamos y gestionamos campañas para que llegue más gente a tu negocio.",
      icon: "megaphone",
    },
    {
      title: "Analítica y medición",
      text: "Configuramos conversiones y medimos resultados para que sepas cómo funciona tu web.",
      icon: "chart-line-up",
    },
    {
      title: "Hosting y dominios",
      text: "Nos encargamos de todo: registro, configuración y renovaciones.",
      icon: "hard-drives",
    },
    {
      title: "Correos empresariales",
      text: "Creamos y configuramos tus cuentas de correo profesional (info@tuempresa.com.ar).",
      icon: "envelope-simple",
    },
    {
      title: "Mantenimiento y soporte",
      text: "Actualizaciones, cambios, backups y soporte técnico siempre que lo necesites.",
      icon: "gear-six",
    },
    {
      title: "Diseño y contenido",
      text: "Imágenes, banners, logos y recursos digitales para que tu marca se vea profesional.",
      icon: "paint-brush",
    },
  ],
  benefits: [
    {
      title: "Genera confianza",
      text: "Los clientes confian mas en negocios que tienen sitio web.",
      icon: "check-circle",
    },
    {
      title: "Te encuentran en Google",
      text: "Estas presente cuando buscan lo que ofreces.",
      icon: "globe",
    },
    {
      title: "Tu negocio trabaja 24/7",
      text: "Tu web esta disponible siempre, incluso cuando no estas.",
      icon: "lightning",
    },
    {
      title: "La IA puede entender que haces",
      text: "La IA accede a la informacion de tu web para recomendar tu negocio.",
      icon: "brain",
    },
    {
      title: "Convertis visitas en consultas",
      text: "Una buena web guia y motiva a tus visitantes a contactarte.",
      icon: "chats-circle",
    },
  ],
  projects: [
    {
      name: "Pinto Dronear",
      description: "Landing page para servicios audiovisuales y filmaciones profesionales con drones.",
      category: "landing",
      tags: ["Landing Page", "Portfolio", "Responsive", "WhatsApp"],
      image: "projectPinto",
      url: "https://pintodronear.com.ar",
    },
    {
      name: "Todo Gas y Plomería",
      description: "Sitio orientado a generar consultas para servicios de gas y plomería.",
      category: "landing",
      tags: ["Landing Page", "Servicios", "WhatsApp", "SEO"],
      image: "projectGas",
      url: "https://todogasyplomeria.com.ar/",
    },
    {
      name: "CD Construcciones",
      description: "Sitio web profesional para una empresa constructora con amplia trayectoria.",
      category: "landing",
      tags: ["Landing Page", "Construcción", "Responsive", "WhatsApp"],
      image: "projectConstruction",
      url: "https://cdconstrucciones.com",
    },
    {
      name: "Consultora Peralta",
      description: "Sitio profesional enfocado en seguridad, higiene y gestión ambiental.",
      category: "landing",
      tags: ["Landing Page", "Profesional", "SEO", "WhatsApp"],
      image: "projectPeralta",
      url: "https://consultoraperalta.com.ar",
    },
    {
      name: "Nortel Automatizaciones",
      description: "Sitio comercial para automatización, seguridad y control de accesos.",
      category: "complete",
      tags: ["Página completa", "Servicios", "WhatsApp", "SEO"],
      image: "projectNortel",
      url: "https://nortelautomatizacion.ar/",
    },
    {
      name: "Indunova",
      description: "Sitio institucional para servicios industriales y navales especializados.",
      category: "complete",
      tags: ["Página completa", "Industria", "SEO", "Responsive"],
      image: "projectIndunova",
      url: "https://indunova.com.ar",
    },
    {
      name: "Geo Domos",
      description: "Web visual para presentar modelos, experiencias de glamping y eventos.",
      category: "complete",
      tags: ["Página completa", "Catálogo", "Responsive", "WhatsApp"],
      image: "projectGeodomos",
      url: "https://geodomos.com.ar",
    },
    {
      name: "Siscom Naval",
      description: "Sitio corporativo para soluciones de navegación y comunicaciones navales.",
      category: "complete",
      tags: ["Página completa", "Naval", "Responsive", "WhatsApp"],
      image: "projectSiscom",
      url: "https://www.siscomnaval.com.ar",
    },
    {
      name: "Automotores Benavidez",
      description: "Sitio comercial para exhibir vehículos y generar nuevas consultas.",
      category: "complete",
      tags: ["Página completa", "Automotores", "Catálogo", "WhatsApp"],
      image: "projectAutomotores",
      url: "https://automotoresbenavidez.com.ar",
    },
  ],
  process: [
    {
      step: "1",
      title: "Hablamos",
      text: "Nos contás tu idea y te asesoramos.",
      icon: "chats-circle",
    },
    {
      step: "2",
      title: "Planificamos",
      text: "Definimos objetivos y te enviamos una propuesta.",
      icon: "file-text",
    },
    {
      step: "3",
      title: "Desarrollamos",
      text: "Diseñamos tu web y la llevamos online.",
      icon: "monitor",
    },
    {
      step: "4",
      title: "Hacés crecer tu negocio",
      text: "Te acompañamos con publicidad y soporte.",
      icon: "chart-line-up",
    },
  ],
  avatars: ["SM", "LC", "AR", "MV"],
  socials: [
    { label: "Facebook", hrefKey: "facebook", icon: "facebook-logo" },
    { label: "Instagram", hrefKey: "instagram", icon: "instagram-logo" },
    // { label: "LinkedIn", hrefKey: "linkedin", icon: "linkedin-logo" },
    { label: "WhatsApp", hrefKey: "whatsapp", icon: "whatsapp-logo" },
  ],
};

const IMAGES = {
  logo: "./imagenes/logo.png",
  heroMockup: "./imagenes/portada.webp",
  mountain: "./imagenes/montanas-footer.png",
  projectConstruction: "./imagenes/trabajos/cd construcciones.webp",
  projectPeralta: "./imagenes/trabajos/consultora peralta.webp",
  projectGeodomos: "./imagenes/trabajos/geodomos.webp",
  projectIndunova: "./imagenes/trabajos/grf consultora.webp",
  projectNortel: "./imagenes/trabajos/nortel automatizaciones.webp",
  projectPinto: "./imagenes/trabajos/pinto dronear.webp",
  projectGas: "./imagenes/trabajos/todogasyplomeria.webp",
  projectSiscom: "./imagenes/trabajos/siscom naval.webp",
  projectAutomotores: "./imagenes/trabajos/automotores benavidez.webp",
};
