const SITE_CONFIG = {
  brand: {
    name: "Puntano Web",
    summary:
      "Diseñamos paginas web modernas y efectivas para ayudar a tu negocio a crecer.",
    copyright: "(c) 2026 Puntano Web. Todos los derechos reservados.",
  },
  contact: {
    whatsappNumber: "5491132595957",
    whatsappMessage:
      "Hola Puntano Web, me contacto desde la web y quiero desarrollar mi sitio web.",
    email: "santiago@puntanoweb.com",
    phone: "+54 9 11 3259-5957",
    address: "San Luis, Argentina",
  },
  links: {
    home: "#inicio",
    portfolio: "#trabajos",
    instagram: "https://www.instagram.com/puntanoweb",
    facebook: "https://www.facebook.com/puntanoweb",
    linkedin: "https://www.linkedin.com/company/puntanoweb",
  },
  navigation: [
    { label: "Inicio", href: "#inicio" },
    { label: "Servicios", href: "#servicios" },
    { label: "Trabajos", href: "#trabajos" },
    { label: "Sobre mí", href: "#sobre-mi" },
    { label: "Contacto", href: "#contacto" },
  ],
  footerServices: [
    "Sitios web",
    "SEO y posicionamiento",
    "Rediseño web",
    "Mantenimiento",
  ],
  services: [
    {
      title: "Diseño y desarrollo web",
      text: "Landing pages y sitios web profesionales, modernos y adaptados a todos los dispositivos.",
      image: "serviceWebDesign",
    },
    {
      title: "Posicionamiento en Google",
      text: "Optimizamos tu web para que te encuentren en buscadores y tengas más visitas.",
      image: "servicePositioning",
    },
    {
      title: "Publicidad en Google Ads",
      text: "Creamos y gestionamos campañas para que llegue más gente a tu negocio.",
      image: "serviceAds",
    },
    {
      title: "Analítica y medición",
      text: "Configuramos conversiones y medimos resultados para que sepas cómo funciona tu web.",
      image: "serviceAnalytics",
    },
    {
      title: "Hosting y dominios",
      text: "Nos encargamos de todo: registro, configuración y renovaciones.",
      image: "serviceHosting",
    },
    {
      title: "Correos empresariales",
      text: "Creamos y configuramos tus cuentas de correo profesional (info@tuempresa.com.ar).",
      image: "serviceEmail",
    },
    {
      title: "Mantenimiento y soporte",
      text: "Actualizaciones, cambios, backups y soporte técnico siempre que lo necesites.",
      image: "serviceMaintenance",
    },
    {
      title: "Diseño y contenido",
      text: "Imágenes, banners, logos y recursos digitales para que tu marca se vea profesional.",
      image: "serviceContent",
    },
  ],
  benefits: [
    {
      title: "Genera confianza",
      text: "Un sitio web profesional transmite seriedad y credibilidad. Tus clientes confían más en negocios que tienen presencia online.",
      highlight: "Una buena imagen te diferencia.",
      highlightIcon: "chart-bar",
      image: "benefitTrust",
    },
    {
      title: "Te encuentran en Google",
      text: "Tu negocio aparece cuando tus clientes buscan lo que ofrecés. Estar en internet te pone al alcance de nuevas oportunidades.",
      highlight: "Más visibilidad, más clientes.",
      highlightIcon: "trend-up",
      image: "benefitGoogle",
    },
    {
      title: "Tu negocio trabaja 24/7",
      text: "Tu web está disponible siempre, incluso cuando no estás. Tus productos o servicios pueden ser consultados en cualquier momento.",
      highlight: "Tu negocio sin límites de horario.",
      highlightIcon: "clock",
      image: "benefitAlwaysOn",
    },
    {
      title: "La IA puede entender qué hacés",
      text: "Las inteligencias artificiales como ChatGPT recomiendan negocios que tienen un sitio web con información clara y actualizada.",
      highlight: "Preparate para el futuro.",
      highlightIcon: "cpu",
      image: "benefitAI",
    },
    {
      title: "Convertís visitas en consultas",
      text: "Una buena web guía a tus visitantes, responde sus dudas y los motiva a contactarte. Más consultas significan más ventas.",
      highlight: "Transformá visitas en oportunidades.",
      highlightIcon: "users-three",
      image: "benefitConversions",
    },
  ],
  projects: [
    {
      name: "Pinto Dronear",
      description:
        "Landing page para servicios audiovisuales y filmaciones profesionales con drones.",
      category: "landing",
      tags: ["Landing Page", "Portfolio", "Responsive", "WhatsApp"],
      image: "projectPinto",
      url: "https://pintodronear.com.ar",
    },
    {
      name: "Todo Gas y Plomería",
      description:
        "Sitio orientado a generar consultas para servicios de gas y plomería.",
      category: "landing",
      tags: ["Landing Page", "Servicios", "WhatsApp", "SEO"],
      image: "projectGas",
      url: "https://todogasyplomeria.com.ar/",
    },
    {
      name: "CD Construcciones",
      description:
        "Sitio web profesional para una empresa constructora con amplia trayectoria.",
      category: "landing",
      tags: ["Landing Page", "Construcción", "Responsive", "WhatsApp"],
      image: "projectConstruction",
      url: "https://cdconstrucciones.com",
    },
    {
      name: "Consultora Peralta",
      description:
        "Sitio profesional enfocado en seguridad, higiene y gestión ambiental.",
      category: "landing",
      tags: ["Landing Page", "Profesional", "SEO", "WhatsApp"],
      image: "projectPeralta",
      url: "https://consultoraperalta.com.ar",
    },
    {
      name: "Nortel Automatizaciones",
      description:
        "Sitio comercial para automatización, seguridad y control de accesos.",
      category: "complete",
      tags: ["Página completa", "Servicios", "WhatsApp", "SEO"],
      image: "projectNortel",
      url: "https://nortelautomatizacion.ar/",
    },
    {
      name: "Indunova",
      description:
        "Sitio institucional para servicios industriales y navales especializados.",
      category: "complete",
      tags: ["Página completa", "Industria", "SEO", "Responsive"],
      image: "projectIndunova",
      url: "https://indunova.com.ar",
    },
    {
      name: "Geo Domos",
      description:
        "Web visual para presentar modelos, experiencias de glamping y eventos.",
      category: "complete",
      tags: ["Página completa", "Catálogo", "Responsive", "WhatsApp"],
      image: "projectGeodomos",
      url: "https://geodomos.com.ar",
    },
    {
      name: "Siscom Naval",
      description:
        "Sitio corporativo para soluciones de navegación y comunicaciones navales.",
      category: "complete",
      tags: ["Página completa", "Naval", "Responsive", "WhatsApp"],
      image: "projectSiscom",
      url: "https://www.siscomnaval.com.ar",
    },
    {
      name: "Automotores Benavidez",
      description:
        "Sitio comercial para exhibir vehículos y generar nuevas consultas.",
      category: "complete",
      tags: ["Página completa", "Automotores", "Catálogo", "WhatsApp"],
      image: "projectAutomotores",
      url: "https://automotoresbenavidez.com.ar",
    },
  ],
  process: [
    {
      step: "1",
      title: "Hablamos",
      text: "Nos contás tu idea, tus objetivos y lo que necesitás. Te asesoramos y resolvemos todas tus dudas.",
      highlight: "Sin compromiso",
      highlightIcon: "clock",
      image: "processTalk",
    },
    {
      step: "2",
      title: "Planificamos",
      text: "Definimos la mejor estrategia, estructura y diseño para tu negocio. Te enviamos una propuesta clara y detallada.",
      highlight: "Objetivos claros",
      highlightIcon: "calendar-dots",
      image: "processPlan",
    },
    {
      step: "3",
      title: "Desarrollamos",
      text: "Diseñamos y desarrollamos tu web cuidando cada detalle. Te mantenemos informado del avance y realizamos ajustes según tu feedback.",
      highlight: "Diseño a medida",
      highlightIcon: "gear-six",
      image: "processDevelop",
    },
    {
      step: "4",
      title: "Hacés crecer tu negocio",
      text: "Publicamos tu web y te acompañamos con soporte y asesoramiento para que aproveches al máximo sus beneficios.",
      highlight: "Resultados reales",
      highlightIcon: "chart-line-up",
      image: "processGrow",
    },
  ],
  avatars: ["SM", "LC", "AR", "MV"],
  socials: [
    { label: "Facebook", hrefKey: "facebook", icon: "facebook-logo" },
    { label: "Instagram", hrefKey: "instagram", icon: "instagram-logo" },
    // { label: "LinkedIn", hrefKey: "linkedin", icon: "linkedin-logo" },
    { label: "WhatsApp", hrefKey: "whatsapp", icon: "whatsapp-logo" },
  ],
};

const IMAGES = {
  logo: "./imagenes/logo.png",
  heroMockup: "./imagenes/portada.webp",
  aboutPhoto: "./imagenes/yo.webp",
  signature: "./imagenes/firma-santiago.png",
  finalPhoto: "./imagenes/yo2.webp",
  serviceWebDesign: "./imagenes/servicios/diseño-desarrollo.webp",
  servicePositioning: "./imagenes/servicios/posicionamiento.webp",
  serviceAds: "./imagenes/servicios/publicidad.webp",
  serviceAnalytics: "./imagenes/servicios/analitica-metrica.webp",
  serviceHosting: "./imagenes/servicios/hosting-dominio.webp",
  serviceEmail: "./imagenes/servicios/email.webp",
  serviceMaintenance: "./imagenes/servicios/mantenimiento.webp",
  serviceContent: "./imagenes/servicios/diseño-contenido.webp",
  benefitTrust: "./imagenes/porque-necesitas-web/confianza.webp",
  benefitGoogle: "./imagenes/porque-necesitas-web/google.webp",
  benefitAlwaysOn: "./imagenes/porque-necesitas-web/24-7.webp",
  benefitAI: "./imagenes/porque-necesitas-web/IA-entender.webp",
  benefitConversions: "./imagenes/porque-necesitas-web/convertir-visitas.webp",
  processTalk: "./imagenes/como-trabajamos/hablamos.webp",
  processPlan: "./imagenes/como-trabajamos/planificamos.webp",
  processDevelop: "./imagenes/como-trabajamos/desarrollamos.webp",
  processGrow: "./imagenes/como-trabajamos/creces.webp",
  mountain: "./imagenes/montanas-footer.png",
  projectConstruction: "./imagenes/trabajos/cd construcciones.webp",
  projectPeralta: "./imagenes/trabajos/consultora peralta.webp",
  projectGeodomos: "./imagenes/trabajos/geodomos.webp",
  projectIndunova: "./imagenes/trabajos/grf consultora.webp",
  projectNortel: "./imagenes/trabajos/nortel automatizaciones.webp",
  projectPinto: "./imagenes/trabajos/pinto dronear.webp",
  projectGas: "./imagenes/trabajos/todogasyplomeria.webp",
  projectSiscom: "./imagenes/trabajos/siscom naval.webp",
  projectAutomotores: "./imagenes/trabajos/automotores benavidez.webp",
};
